data:
  class_path: pyad.datamanager.dataset.TabularDataset
  init_args:
    batch_size: 1024
    data_dir: C:\Users\verj2009\NRCAN\git\anomaly_detection_NRCAN\data\Thyroid\thyroid.mat
    scaler: standard