model:
  class_path: pyad.models.one_class.DeepSVDD
  init_args:
    feature_dim: 128
    hidden_dims:
      - 32
      - 64
    activation: relu
    eps: 0.1
    weight_decay: 1e-4
    lr: 1e-4
    n_epochs: 200
trainer:
  init_args:
    enable_checkpoints: False
    val_check_interval: -1
data:
  init_args:
    batch_size: 1024