model:
  class_path: pyad.models.density.DSEBM
  init_args:
    fc_1_out: 64
    fc_2_out: 128
    batch_size: 1024
    score_metric: reconstruction
    weight_decay: 1e-4
    lr: 1e-4
    n_epochs: 200