model:
  class_path: pyad.models.reconstruction.MemAE
  init_args:
    mem_dim: 50
    latent_dim: 1
    enc_hidden_dims:
      - 12
      - 4
    shrink_thresh: 0.0025
    alpha: 2e-4
    activation: relu
    weight_decay: 1e-4
    lr: 1e-4
    n_epochs: 200