model:
  class_path: pyad.models.selfsup.NeuTraLAD
  init_args:
    weight_decay: 1e-5
    lr: 0.001
    n_epochs: 200
    n_transforms: 11
    trans_type: res
    temperature: 0.1
    trans_hidden_dims:
      - 24
    enc_hidden_dims:
      - 24
      - 24
      - 24
      - 24
      - 24
    use_batch_norm: True
data:
  init_args:
    batch_size: 128
    scaler: none