model:
  class_path: pyad.models.selfsup.GOAD
  init_args:
    lr: 1e-4
    n_transforms: 256
    feature_dim: 128
    num_hidden_nodes: 128
    batch_size: 64
    n_layers: 5
    eps: 0
    lamb: 0.1
    margin: 1
trainer:
  class_path: pyad.models.trainer.ModuleTrainer
  init_args:
    n_runs: 20
    val_check_interval: 5
    max_epochs: 25
    enable_checkpoints: True
    checkpoint_interval: 5
    logger:
      class_path: pyad.loggers.NeptuneLogger
data:
  init_args:
    batch_size: 64