model:
  class_path: pyad.models.selfsup.NeuTraLAD
  init_args:
    weight_decay: 0.0
    lr: 0.0005
    n_transforms: 11
    trans_type: mul
    temperature: 0.1
    trans_hidden_dims:
      - 100
    enc_hidden_dims:
      - 64
      - 64
      - 64
      - 64
      - 32
trainer:
  class_path: pyad.models.trainer.ModuleTrainer
  init_args:
    n_runs: 20
    val_check_interval: 5
    max_epochs: 1
    enable_checkpoints: True
    checkpoint_interval: 5
    logger:
      class_path: pyad.loggers.NeptuneLogger
data:
  init_args:
    batch_size: 1000