name: pyad-2
channels:
  - conda-forge
  - nvidia
  - pytorch
dependencies:
  - python=3.8
  - pytorch=1.13
  - pytorch-cuda=11.6
  - conda-forge::neptune-client
  - pip
  - pip:
    - numpy
    - matplotlib
    - pytorch-lightning
    - scikit-learn~=1.2.1
    - tqdm
    - scipy
    - pandas
    - jsonargparse