model:
  class_path: pyad.models.density.DAGMM
  init_args:
    n_mixtures: 2
    gmm_hidden_dims:
    - 10
    latent_dim: 2
    ae_hidden_dims:
    - 32
    dropout_rate: 0.5
    ae_activation: tanh
    gmm_activation: tanh
    lamb_1: 0.1
    lamb_2: 0.005
    reg_covar: 1e-12
    weight_decay: 1e-6
    lr: 1e-4
trainer:
  class_path: pyad.models.trainer.ModuleTrainer
  init_args:
    max_epochs: 100
    n_runs: 5
    val_check_interval: 10
    enable_checkpoints: True
    checkpoint_interval: 5
    logger:
      class_path: pyad.loggers.NeptuneLogger