model:
  class_path: pyad.lightning.transformers.LitGOAD
  init_args:
    weight_decay: 1e-4
    lr: 1e-4
    n_transforms: 64
    feature_dim: 64
    num_hidden_nodes: 32
    batch_size: 1024
    n_layers: 5
    eps: 0
    lamb: 0.1
    margin: 1
trainer:
  class_path: pyad.models.trainer.ModuleTrainer
  init_args:
    max_epochs: 25
    n_runs: 5
    val_check_interval: 10
    enable_checkpoints: True
    checkpoint_interval: 5
    logger:
      class_path: pyad.loggers.NeptuneLogger