data:
  class_path: pyad.datamanager.dataset.TabularDataset
  init_args:
    batch_size: 1024
    data_dir: ./data/KDD10/kdd10.csv
    scaler: minmax
    labels_col_name: Category
    binary_labels_col_name: label