model:
  class_path: pyad.models.density.SOMDAGMM
  init_args:
    n_soms: 1
    weight_decay: 1e-6
    lr: 1e-4
    dagmm:
      class_path: pyad.models.density.DAGMM
      init_args:
        n_mixtures: 2
        gmm_hidden_dims:
        - 10
        latent_dim: 2
        ae_hidden_dims:
        - 32
        dropout_rate: 0.5
        ae_activation: tanh
        gmm_activation: tanh
        lamb_1: 0.1
        lamb_2: 0.005
        reg_covar: 1e-12
        weight_decay: 1e-6
        lr: 1e-4