trainer:
  class_path: pyad.models.trainer.ModuleTrainer
  init_args:
    max_epochs: 200
    n_runs: 20
    val_check_interval: None
    enable_checkpoints: True
    checkpoint_interval: 5
    logger:
      class_path: pyad.loggers.NeptuneLogger