trainer:
  class_path: pyad.models.trainer.ModuleTrainer
  init_args:
    max_epochs: 200
    n_runs: 20
    val_check_interval: 1
    enable_checkpoints: True
    checkpoint_interval: 5
    normal_sampling_seed: 42
#    logger:
#      class_path: pyad.loggers.NeptuneLogger