model:
  class_path: pyad.models.reconstruction.AutoEncoder
  init_args:
    latent_dim: 2
    hidden_dims:
      - 10
    activation: relu
    reg: 0.5
    weight_decay: 1e-4
    lr: 1e-4
    n_epochs: 200