model:
  class_path: pyad.models.selfsup.GOAD
  init_args:
    weight_decay: 1e-4
    lr: 1e-4
    n_transforms: 256
    feature_dim: 32
    num_hidden_nodes: 8
    batch_size: 128
    n_layers: 0
    eps: 0
    lamb: 0.1
    margin: 1
trainer:
    class_path: pyad.models.trainer.ModuleTrainer
    init_args:
      max_epochs: 1
      n_runs: 20
      val_check_interval: 1
      enable_checkpoints: True
      checkpoint_interval: 5
      logger:
        class_path: pyad.loggers.NeptuneLogger