model:
  class_path: pyad.models.selfsup.NeuTraLAD
  init_args:
    weight_decay: 1e-5
    lr: 0.0001
    n_transforms: 11
    trans_type: res
    temperature: 0.1
    trans_hidden_dims:
      - 200
    enc_hidden_dims:
      - 64
      - 64
      - 64
      - 64
      - 64
      - 32
data:
  init_args:
    batch_size: 128
    scaler: minmax